
package sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import sample.HelloWorld;
import sample.HelloWorldService;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://sample/", wsdlLocation = "http://localhost:8080/helloworld/HelloWorldService?wsdl")
public class HelloWorldService
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName HELLOWORLDSERVICE = new QName("http://sample/", "HelloWorldService");
    private final static QName HELLOWORLDPORT = new QName("http://sample/", "HelloWorldPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/helloworld/HelloWorldService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, HELLOWORLDSERVICE);
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorld getHelloWorldPort() {
        return (HelloWorld)super.getPort(HELLOWORLDPORT, HelloWorld.class);
    }

}
